[project]
name = "comfyui_nvidia_vfx_nodes"
description = "ComfyUI nodes for VFX professionals\nThis extension provides GPU-accelerated nodes powered by Nvidia RTX technology, including super resolution, frame generation and SDR-to-HDR conversion."
version = "0.2.0"
license = "LICENSE"
dependencies = [
  "nvidia-vfx"
]

[project.urls]
Repository = "https://github.com/Comfy-Org/Nvidia_RTX_Nodes_ComfyUI"

[tool.comfy]
PublisherId = "comfyui"
DisplayName = "ComfyUI Nvidia VFX Nodes"
Icon = "https://raw.githubusercontent.com/Comfy-Org/Nvidia_RTX_Nodes_ComfyUI/refs/heads/main/icon.png"
